name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install project
        run: yarn install

      - name: Build project
        run: yarn run build --if-present

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: setup-checkout-${{ github.run_id }}
          path: ${{ github.workspace }}/**/*

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Get Cached Checkout
        uses: actions/download-artifact@v3
        with:
          name: setup-checkout-${{ github.run_id }}

      - name: Run lint
        run: yarn lint

  compile:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Get Cached Checkout
        uses: actions/download-artifact@v3
        with:
          name: setup-checkout-${{ github.run_id }}

      - name: Run tsc
        uses: icrawl/action-tsc@v1

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Get Cached Checkout
        uses: actions/download-artifact@v3
        with:
          name: setup-checkout-${{ github.run_id }}

      - name: Run tests & coverage
        run: yarn test --coverage && bash <(curl -s https://codecov.io/bash)

  coverage:
    needs: [setup, test]
    runs-on: ubuntu-latest
    steps:
      - name: Get Cached Checkout
        uses: actions/download-artifact@v3
        with:
          name: setup-checkout-${{ github.run_id }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
